version: '3.1'

services:
  db:
    image: postgres:13.5
    privileged: true
    restart: always
    ports:
      - 54321:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: restapi
      POSTGRES_DB: todo

  backend:
    build: ./backend
    privileged: true
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
    command: bash -c "
        python manage.py migrate &&
        gunicorn backend.wsgi -b 0.0.0.0:8080
      "
    environment:
      DJANGO_SETTINGS_MODULE: 'backend.settings.prod'

  nginx:
    build: ./nginx
    privileged: true
    ports:
      - 8000:80
    depends_on:
      - backend

  frontend:
    build: ./frontend
    privileged: true
    ports:
      - 80:80
    depends_on:
      - backend