# Generated by Django 3.2.12 on 2022-02-21 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restuser',
            name='age',
            field=models.PositiveSmallIntegerField(default=18),
        ),
        migrations.AddField(
            model_name='restuser',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='restuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
